language: en-US
reviews:
  profile: chill
  path_filters:
    - "!pnpm-lock.yaml"
    - "!**/node_modules/**"
    - "!.next/**"
    - "!convex/_generated/**"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
